### ISSUE TITLE
Image Source

### ISSUE THREAD

**Issue by bmitchinson** [natmeow/racoon-webxr-viewer#2]
Wait, I could be having a fever dream but, is this my image haha? It looks super familiar to me, maybe I've just seen your work before?

https://github.com/bmitchinson/racoon-webxr-viewer/blob/master/images/converted_left.jpg

Wondering if there's a chance you've come across my work in the past: https://devpost.com/software/oculus-mobile-photo-viewer

**Comment by bmitchinson** [comment]
Wait I just confirmed it's mine from checking my personal photo library hahahaha. How did you come across this one :)

**Comment by caffeinum** [comment]
oh wow haha sorry!!

i think i took a random
image from the internet as demo?

also you might have seen my website a few years ago and uploaded your image there?

i can remove it asap if you ask

**Comment by bmitchinson** [comment]
No need to remove! Was just curious :) hope you're well.
